### PR TITLE
Added Bubble sort algorithm in java

### PR DESCRIPTION
**Pull request by agesa3**

### CODE REVIEW

**Comment by soer7022** [comment]
Thank you for The submission! Please add your name to CONTRIBUTORS.md :)

**Comment by agesa3** [comment]
> Thank you for The submission! Please add your name to CONTRIBUTORS.md :)

Done

**Comment by agesa3** [comment]
hello I added my name to CONTRIBUTORS.md.

**Comment by soer7022** [comment]
I don't see the change, please double check

**Pull request merged**
